name: Sync Bundle

on:
  push:
    paths:
      - 'bundle/**'

  workflow_dispatch: # Manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout RBC repo
      uses: actions/checkout@v3
      with:
        repository: DevOps-automation-tasks/RHOAI-Build-Config
        path: rbc-repo
        token: ${{ secrets.BUNDLE_SYNC_TOKEN }}

    - name: Checkout Operator repo
      uses: actions/checkout@v3
      with:
        repository: DevOps-automation-tasks/rhods-operator
        path: operator-repo
        token: ${{ secrets.BUNDLE_SYNC_TOKEN }}

    - name: Fetch branches from Operator repo
      run: |
        cd operator-repo
        git fetch --all
        git branch -r

    - name: Determine release branches
      id: branches
      run: |
        cd operator-repo
        branches=$(git branch -r | grep 'origin/rhoai-' | sed 's/origin\///' | sort -V | tail -n 2)
        echo "branches=$branches" >> $GITHUB_ENV

    - name: Sync bundle for each branch
      run: |
        for branch in $(echo ${{ env.branches }}); do
          echo "Syncing branch: $branch"
          cd operator-repo
          
          # Checkout the branch from the operator repo
          git checkout $branch
          
          # Prepare bundle sync (remove channels, default channel, replaces, and skip ranges)
          # Example commands - adjust based on actual commands needed
          # remove-channels-command

          # Sync CSV, metadata, CRDs
          # Syncing commands here - adjust based on actual sync process
          # sync-csv-command
          # sync-metadata-command
          # sync-crds-command
          
          # Copy the updated bundle Dockerfile to RBC repo
          cp Dockerfile ../rbc-repo/bundle/Dockerfile
          
          # Sync other bundle files to RBC repo
          cp -r ./* ../rbc-repo/bundle/

          # Add, commit, and push changes to RBC repo
          cd ../rbc-repo
          git add bundle/
          git commit -m "Update bundle for branch $branch"
          git push origin $branch

        done

    - name: Clean up
      run: |
        rm -rf rbc-repo
        rm -rf operator-repo
