name: Sync Bundle
on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Operator Repo
        uses: actions/checkout@v3
        with:
          repository: DevOps-automation-tasks/rhods-operator
          path: operator-repo
        id: checkout-operator-repo

      - name: Checkout RBC Repo
        uses: actions/checkout@v3
        with:
          repository: DevOps-automation-tasks/RHOAI-Build-Config
          path: rbc-repo
        id: checkout-rbc-repo

      - name: Get Branches
        id: get-branches
        run: |
          # Fetch branches from the Operator repo
          cd operator-repo
          git fetch --all
          operator_branches=$(git branch -r | grep 'origin/rhoai-' | sed 's/origin\///' | sort -V)
          echo "Operator branches: $operator_branches"
          echo "$operator_branches" > ../branches-operator.txt
          cd ..

          # Fetch branches from the RBC repo
          cd rbc-repo
          git fetch --all
          rbc_branches=$(git branch -r | grep 'origin/rhoai-' | sed 's/origin\///' | sort -V)
          echo "RBC branches: $rbc_branches"
          echo "$rbc_branches" > ../branches-rbc.txt
          cd ..

          # Find latest and previous branches
          latest_branch=$(head -n 1 branches-operator.txt)
          previous_branch=$(sed -n '2p' branches-operator.txt)
          echo "Latest branch: $latest_branch"
          echo "Previous branch: $previous_branch"

      - name: Sync Branches
        run: |
          # Read branches from the files
          operator_branches=$(cat branches-operator.txt | tr '\n' ' ')
          rbc_branches=$(cat branches-rbc.txt | tr '\n' ' ')
          
          if [ -z "$operator_branches" ] || [ -z "$rbc_branches" ]; then
            echo "No branches found."
            exit 1
          fi
          
          # Convert the space-separated list to a bash array
          operator_branches_array=($operator_branches)
          rbc_branches_array=($rbc_branches)
          
          if [ ${#operator_branches_array[@]} -lt 2 ]; then
            echo "Not enough branches found."
            exit 1
          fi
          
          # Parse the array
          latest_branch=${operator_branches_array[0]}
          previous_branch=${operator_branches_array[1]}
          
          echo "Latest branch: $latest_branch"
          echo "Previous branch: $previous_branch"
          
          branches=("${latest_branch}" "${previous_branch}")
          
          for branch in "${branches[@]}"; do
            echo "Syncing for branch: $branch"
            
            # Check if the branch exists in both repos
            if [[ " ${rbc_branches_array[@]} " =~ " ${branch} " ]] && [[ " ${operator_branches_array[@]} " =~ " ${branch} " ]]; then
              echo "Branch $branch exists in both repos. Syncing..."
              
              # Navigate to the RBC repo directory
              cd rbc-repo
              git checkout $branch

              # Navigate to the Operator repo directory
              cd ../operator-repo
              git checkout $branch

              # Sync the bundle files from the Operator repo
              rsync -av --delete ../operator-repo/bundle/ ../rbc-repo/bundle/

              # Overwrite the Dockerfile
              cp ../operator-repo/bundle/Dockerfile ../rbc-repo/bundle/

              # Navigate back to RBC repo
              cd ../rbc-repo

              git add .
              git commit -m "Sync bundle from operator repo for $branch"
              git push origin $branch
            else
              echo "Branch $branch does not exist in one or both repos. Skipping..."
            fi
            
            # Navigate back to the root directory
            cd ..
          done

