name: Sync Bundle to RBC Repo

on:
  push:
    paths:
      - 'bundle/**'
    branches:
      - 'rhoai-x.y*'

  workflow_dispatch:  # This adds the manual trigger

jobs:
  sync-bundle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout operator repo
        uses: actions/checkout@v3
        with:
          repository: DevOps-automation-tasks/rhods-operator
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref }}

      - name: Remove olm.skipRange from the CSV file
        run: |
          sed -i '/ olm.skipRange/d' bundle/manifests/rhods-operator.clusterserviceversion.yaml

      - name: Checkout RBC repo
        uses: actions/checkout@v3
        with:
          repository: DevOps-automation-tasks/RHOAI-Build-Config
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref }}

      - name: Sync bundle to RBC repo
        run: |
          cp -r bundle/* ../RHOAI-Build-Config/bundle/
          cp bundle/Dockerfile ../RHOAI-Build-Config/bundle/Dockerfile

      - name: Retain existing image digests
        run: |
         
