name: 01 RBC Repo

on:
  push:
    paths:
      - 'bundle/**'
      - 'Dockerfiles/bundle.Dockerfile'
    branches:
      - 'rhoai-x.y*'

  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  sync-bundle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout operator repo
        uses: actions/checkout@v3
        with:
          repository: DevOps-automation-tasks/rhods-operator
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref }}

      - name: Remove olm.skipRange from the CSV file
        run: |
          sed -i '/ olm.skipRange/d' bundle/manifests/rhods-operator.clusterserviceversion.yaml

      - name: Checkout RBC repo
        uses: actions/checkout@v3
        with:
          repository: DevOps-automation-tasks/RHOAI-Build-Config
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref }}

      - name: Sync bundle to RBC repo
        run: |
          cp -r bundle/* bundle/
          cp Dockerfiles/bundle.Dockerfile bundle/Dockerfile

      - name: Retain existing image digests
        run: |
          # Logic to retain existing image digests
          echo "Retain image digests logic goes here."

      - name: Commit and push changes to RBC repo
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Sync bundle changes from operator repo"
          git push origin ${{ github.ref }}
