name: Sync Bundle

on:
  push:
    paths:
      - 'path/to/bundle/files/**'
    branches:
      - 'main'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout RBC repo
        uses: actions/checkout@v3
        with:
          repository: DevOps-automation-tasks/RHOAI-Build-Config
          path: rbc-repo

      - name: Checkout Operator repo
        uses: actions/checkout@v3
        with:
          repository: DevOps-automation-tasks/rhods-operator
          path: operator-repo
          ref: ${{ github.ref }}

      - name: Sync Bundle Files
        run: |
          # Define directories
          OPERATOR_BUNDLE_DIR="operator-repo/path/to/bundle/files"
          RBC_BUNDLE_DIR="rbc-repo/bundle"

          # Copy bundle files from operator repo to RBC repo
          echo "Syncing bundle files from operator repo to RBC repo..."
          rsync -av --delete "$OPERATOR_BUNDLE_DIR/" "$RBC_BUNDLE_DIR/"

      - name: Remove Old Files
        run: |
          # Remove old files from RBC repo
          echo "Removing old files from RBC repo..."
          find rbc-repo/bundle -type f -not -path 'rbc-repo/bundle/new-files/*' -delete

      - name: Commit Changes
        run: |
          cd rbc-repo
          git add .
          git commit -m "Sync bundle from operator repo"
          git push origin main

      - name: Validate Sync
        run: |
          echo "Validating sync..."
          # Here you can add any validation steps if needed

      - name: Clean Up
        run: |
          # Remove temporary directories
          rm -rf rbc-repo
          rm -rf operator-repo
