name: Sync Bundle

on:
  push:
    paths:
      - 'path/to/bundle/files/**'
  workflow_dispatch:

jobs:
  sync-bundle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout rhods-operator repository
        uses: actions/checkout@v3
        with:
          repository: DevOps-automation-tasks/rhods-operator
          path: operator-repo

      - name: Checkout RHOAI-Build-Config repository
        uses: actions/checkout@v3
        with:
          repository: DevOps-automation-tasks/RHOAI-Build-Config
          path: rbc-repo

      - name: Fetch all branches and determine latest
        run: |
          cd operator-repo
          git fetch --all
          git branch -r | grep -v '\->' | sed 's/origin\///' | sort -V | tail -n 2 > latest_branches.txt

      - name: Read latest branches
        run: |
          latest_branches=$(cat operator-repo/latest_branches.txt)
          latest_branch=$(echo "$latest_branches" | head -n 1)
          second_latest_branch=$(echo "$latest_branches" | tail -n 1)
          echo "LATEST_BRANCH=${latest_branch}" >> $GITHUB_ENV
          echo "SECOND_LATEST_BRANCH=${second_latest_branch}" >> $GITHUB_ENV

      - name: Debug output
        run: |
          echo "LATEST_BRANCH=${LATEST_BRANCH}"
          echo "SECOND_LATEST_BRANCH=${SECOND_LATEST_BRANCH}"

      - name: Sync Bundle Files
        run: |
          cd rbc-repo
          # Remove existing channels, default channel, replaces, and skip ranges
          # Ensure this is compatible with your setup
          find path/to/bundle -name '*.csv' -exec sed -i '/channels:/d' {} \;
          find path/to/bundle -name '*.csv' -exec sed -i '/default_channel:/d' {} \;
          find path/to/bundle -name '*.csv' -exec sed -i '/replaces:/d' {} \;
          find path/to/bundle -name '*.csv' -exec sed -i '/skip_ranges:/d' {} \;

          # Overwrite the bundle Dockerfile
          cp ../operator-repo/path/to/bundle/Dockerfile path/to/bundle/Dockerfile

          # Sync CSV, metadata, and custom resource definitions
          cp -r ../operator-repo/path/to/bundle/* path/to/bundle/

      - name: Commit and push changes
        run: |
          cd rbc-repo
          git add .
          git commit -m "Sync bundle from ${LATEST_BRANCH} and ${SECOND_LATEST_BRANCH}"
          git push

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
