name: Sync Bundle

on:
  push:
    paths:
      - 'path/to/bundle/files/**'
  workflow_dispatch:

jobs:
  sync-bundle:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout rhods-operator repository
      uses: actions/checkout@v3
      with:
        repository: DevOps-automation-tasks/rhods-operator
        path: operator-repo

    - name: Checkout RHOAI-Build-Config repository
      uses: actions/checkout@v3
      with:
        repository: DevOps-automation-tasks/RHOAI-Build-Config
        path: rbc-repo

    - name: Fetch all branches from rhods-operator
      id: fetch-branches
      run: |
        cd operator-repo
        git fetch --all
        BRANCHES=$(git branch -r | grep 'origin/rhoai-x.y' | sed 's/origin\///' | sort -V)
        echo "Branches: $BRANCHES"
        LATEST_BRANCH=$(echo "$BRANCHES" | tail -n 1)
        SECOND_LATEST_BRANCH=$(echo "$BRANCHES" | tail -n 2 | head -n 1)
        echo "LATEST_BRANCH=${LATEST_BRANCH}" >> $GITHUB_ENV
        echo "SECOND_LATEST_BRANCH=${SECOND_LATEST_BRANCH}" >> $GITHUB_ENV

    - name: Echo Latest and Second Latest Branches
      run: |
        echo "LATEST_BRANCH=${LATEST_BRANCH}"
        echo "SECOND_LATEST_BRANCH=${SECOND_LATEST_BRANCH}"

    - name: Sync bundle
      run: |
        # Your sync logic here, using the branches from $LATEST_BRANCH and $SECOND_LATEST_BRANCH
        # For example:
        echo "Syncing bundle with branches ${LATEST_BRANCH} and ${SECOND_LATEST_BRANCH}..."
        # You can add the actual commands for syncing here.

    - name: Overwrite Bundle Dockerfile
      run: |
        # Your logic to overwrite the Dockerfile, if needed
        cp operator-repo/Dockerfiles/bundle.Dockerfile rbc-repo/bundle/Dockerfile
        echo "Overwritten the bundle Dockerfile"
