name: Sync Bundle

on:
  push:
    paths:
      - 'path/to/bundle/files/**'
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout operator repo
        uses: actions/checkout@v3
        with:
          repository: DevOps-automation-tasks/rhods-operator
          path: operator-repo

      - name: Checkout RBC repo
        uses: actions/checkout@v3
        with:
          repository: DevOps-automation-tasks/RHOAI-Build-Config
          path: rbc-repo
          token: ${{ secrets.BUNDLE_SYNC_TOKEN }}

      - name: Get latest rhoai-x.y branches
        id: get-branches
        run: |
          curl -H "Authorization: token ${{ secrets.BUNDLE_SYNC_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/DevOps-automation-tasks/rhods-operator/branches \
               | jq -r '.[] | select(.name | startswith("rhoai-")) | .name' \
               | head -n 2 > latest_branches.txt

      - name: Read branch names
        id: branches
        run: |
          latest_branches=$(cat latest_branches.txt)
          echo "::set-output name=branches::$latest_branches"

      - name: Fetch branches
        id: fetch-branches
        run: |
          branches=($(echo "${{ steps.branches.outputs.branches }}" | tr '\n' ' '))
          latest_branch="${branches[0]}"
          second_latest_branch="${branches[1]}"
          echo "LATEST_BRANCH=$latest_branch" >> $GITHUB_ENV
          echo "SECOND_LATEST_BRANCH=$second_latest_branch" >> $GITHUB_ENV

      - name: Sync Bundle
        run: |
          latest_branch=${LATEST_BRANCH}
          second_latest_branch=${SECOND_LATEST_BRANCH}

          echo "Syncing bundle for branches: $latest_branch and $second_latest_branch"

          # Example commands to perform the sync process
          # 1. Remove channels, default channel, replaces, and skip ranges from the operator repo.
          # 2. Sync CSV, metadata, and all custom resource definitions.
          # 3. Overwrite bundle Dockerfile in the RBC repo.

          # Example commands (replace these with actual commands/scripts):
          cd operator-repo/path/to/bundle/files
          rm -rf channels default-channel replaces skip-ranges

          # Sync bundle files
          cp -r * ../../rbc-repo/bundle/

          cd ../../rbc-repo
          # Overwrite Dockerfile (Example command, adjust as needed)
          cp -f bundle/Dockerfile .

      - name: Commit and push changes to RBC repo
        run: |
          cd rbc-repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Sync bundle from operator repo"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.BUNDLE_SYNC_TOKEN }}
