name: Sync Bundle

on:
  push:
    paths:
      - 'path/to/bundle/files/**'
    branches:
      - 'main'
  workflow_dispatch:  # Allows manual triggering

jobs:
  determine-branches:
    runs-on: ubuntu-latest
    outputs:
      latest-branch: ${{ steps.get-latest.outputs.latest }}
      second-latest-branch: ${{ steps.get-second-latest.outputs.second-latest }}

    steps:
      - name: Checkout Operator Repo
        uses: actions/checkout@v3
        with:
          repository: DevOps-automation-tasks/rhods-operator
          path: operator-repo

      - name: Get Branch List
        id: get-branches
        run: |
          branches=$(gh api repos/DevOps-automation-tasks/rhods-operator/branches --jq '.[].name' | sort -r)
          echo "Branches: $branches"
          echo "branches=$branches" >> $GITHUB_ENV

      - name: Set Latest and Second Latest Branch
        id: get-latest
        run: |
          branches=(${{ env.branches }})
          latest=${branches[0]}
          second_latest=${branches[1]}
          echo "Latest Branch: $latest"
          echo "Second Latest Branch: $second_latest"
          echo "latest=$latest" >> $GITHUB_ENV
          echo "second-latest=$second_latest" >> $GITHUB_ENV

  sync-bundle:
    needs: determine-branches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout RBC Repo
        uses: actions/checkout@v3
        with:
          repository: DevOps-automation-tasks/RHOAI-Build-Config
          path: rbc-repo

      - name: Checkout Operator Repo
        uses: actions/checkout@v3
        with:
          repository: DevOps-automation-tasks/rhods-operator
          path: operator-repo
          ref: ${{ needs.determine-branches.outputs.latest }}

      - name: Sync Bundle Files
        run: |
          OPERATOR_BUNDLE_DIR="operator-repo/path/to/bundle/files"
          RBC_BUNDLE_DIR="rbc-repo/bundle"
          echo "Syncing bundle files from operator repo to RBC repo..."
          rsync -av --delete "$OPERATOR_BUNDLE_DIR/" "$RBC_BUNDLE_DIR/"

      - name: Remove Old Files
        run: |
          echo "Removing old files from RBC repo..."
          find rbc-repo/bundle -type f -not -path 'rbc-repo/bundle/new-files/*' -delete

      - name: Commit Changes
        run: |
          cd rbc-repo
          git add .
          git commit -m "Sync bundle from operator repo"
          git push origin main

      - name: Validate Sync
        run: |
          echo "Validating sync..."
          # Add any validation steps if needed

      - name: Clean Up
        run: |
          rm -rf rbc-repo
          rm -rf operator-repo
